version: "3.3"
services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    image: hainguyen267/ima-talk-fe:0.5
    ports:
      - "80:3000"
    environment:
      # - REACT_APP_BACKEND_URL=http://localhost:8080
      # - REACT_APP_BACKEND_WEBSOCKET_URL=http://localhost:8100
      - REACT_APP_BACKEND_URL=http://35.247.189.43:8080
      - REACT_APP_BACKEND_WEBSOCKET_URL=http://35.247.189.43:8100

  registry-service:
    image: hainguyen267/ima-talk-registry-service:0.5
    ports:
      - "8761:8761"
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--spider",
          "-S",
          "http://localhost:8761/actuator/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - eureka.instance.hostname=host.docker.internal

  api-gateway:
    image: hainguyen267/ima-talk-api-gateway:0.51
    # restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - eureka.client.service-url.defaultZone=http://registry-service:8761/eureka/
    depends_on:
      registry-service:
        condition: service_healthy

  auth-service:
    image: hainguyen267/ima-talk-auth-service:0.5
    restart: on-failure
    ports:
      - "8101:8101"
    environment:
      - eureka.client.service-url.defaultZone=http://registry-service:8761/eureka/
      # - spring.kafka.bootstrap-servers=35.247.189.43:9092
      - spring.kafka.bootstrap-servers=34.128.67.66:9092
    depends_on:
      registry-service:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--spider",
          "-S",
          "http://localhost:8101/api/auth/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 5

  chat-service:
    image: hainguyen267/ima-talk-chat-service:0.51
    restart: on-failure
    ports:
      - "8102:8102"
    environment:
      - eureka.client.service-url.defaultZone=http://registry-service:8761/eureka/
      - server.port=8102
      # - spring.kafka.bootstrap-servers=35.247.189.43:9092
      - spring.kafka.bootstrap-servers=34.128.67.66:9092
    depends_on:
      registry-service:
        condition: service_healthy
       
  notification-service:
    image: hainguyen267/ima-talk-notification-service:0.5
    restart: on-failure
    ports:
      - "8103:8103"
    environment:
      - eureka.client.service-url.defaultZone=http://registry-service:8761/eureka/
      - server.port=8103
      # - spring.kafka.bootstrap-servers=35.247.189.43:9092
      - spring.kafka.bootstrap-servers=34.128.67.66:9092
    depends_on:
      registry-service:
        condition: service_healthy
       
  search-service:
    image: hainguyen267/ima-talk-search-service:0.5
    restart: on-failure
    ports:
      - "8105:8105"
    environment:
      - eureka.client.service-url.defaultZone=http://registry-service:8761/eureka/
      - server.port=8105
      # - spring.kafka.bootstrap-servers=35.247.189.43:9092
      - spring.kafka.bootstrap-servers=34.128.67.66:9092
      - mysql_database=ima-talk
      - mysql_username=root
      - mysql_host=mysql
      - mysql_password=my_password
    depends_on:
      registry-service:
        condition: service_healthy
      mysql:
        condition: service_healthy
  user-service:
    image: hainguyen267/ima-talk-user-service:0.51
    restart: on-failure
    ports:
      - "8104:8104"
    environment:
      - eureka.client.service-url.defaultZone=http://registry-service:8761/eureka/
      - server.port=8104
      # - spring.kafka.bootstrap-servers=35.247.189.43:9092
      - spring.kafka.bootstrap-servers=34.128.67.66:9092
      - mysql_database=ima-talk
      - mysql_username=root
      - mysql_host=mysql
      - mysql_password=my_password
    depends_on:
      registry-service:
        condition: service_healthy
      mysql:
        condition: service_healthy
  ws-handler-service:
    image: hainguyen267/ima-talk-ws-handler-service:0.5
    restart: on-failure
    ports:
      - "8100:8100"
    environment:
      - eureka.client.service-url.defaultZone=http://registry-service:8761/eureka/
      - server.port=8100
      # - spring.kafka.bootstrap-servers=35.247.189.43:9092
      - spring.kafka.bootstrap-servers=34.128.67.66:9092
      # - FRONT_END_URL=http://35.247.189.43
      - FRONT_END_URL=http://imatalk.online
      # - FRONT_END_URL=http://localhost
    depends_on:
      registry-service:
        condition: service_healthy
       
volumes:
  mysql_data:
