version: "3.8"
services:
  frontend:
    image: hainguyen267/ima-talk-ui:0.21
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://34.126.76.241:8081
  backend:
    image: hainguyen267/ima-talk:0.21
    ports:
      - "8081:8080"

